on: push

name: Re-make plot

jobs:
  render:
    name: Re-make plot
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install R deps
        run: Rscript -e 'install.packages(c("knitr", "ggplot2", "dplyr", "googlesheets4"))'
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: Re-make plot
        run: Rscript -e 'knitr::knit("README.Rmd")'
      - name: Commit results
        run: |
          git config user.email "myrmecocystus@gmail.com"
          git config user.name "Scott Chamberlain"
          git commit figure/plot-1.png -m 'Re-build plot' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
